### ISSUE TITLE
Incorrect wavenumbers for IASI-NG

### ISSUE THREAD

**Issue by wx20jjung** [JCSDA/CRTM_coef#6]
I found an inconsistency with the wavenumbers for IASI-NG.  Here is the region in question:

iasi chan         4037   1149.50000000000
iasi chan         4038   1149.62500000000
iasi chan         4039   1149.75000000000
iasi chan         4040   1150.00000000000
iasi chan         4041   1150.12500000000
iasi chan         4042   1150.25000000000
iasi chan         4043   1150.37500000000

Channel 4040 should be 1149.875.  All channels from 4040 and beyond are off by 0.125

**Comment by BenjaminTJohnson** [comment]
@wx20jjung 
Band 1 ends at:
```
4026, 4027, 4028, 4029, 4030, 4031, 4032, 4033, 4034, 4035, 4036, 4037, 
    4038, 4039 ;
```
Wavenumbers for the last few channels in Band 1:
```
  1148.25, 1148.375, 1148.5, 1148.625, 1148.75, 1148.875, 1149, 1149.125, 
    1149.25, 1149.375, 1149.5, 1149.625, 1149.75 ;
```

And for the beginning of Band 2:
```
 Sensor_Channel = 4040, 4041, 4042, 4043, 4044, 4045, 4046, 4047, 4048, 4049, 
    4050, 4051, 4052, 4053, 4054, 4055, 4056, 4057, 4058, 4059, 4060, 4061, 
```
and the wavenumbers:
```
 Wavenumber = 1150, 1150.125, 1150.25, 1150.375, 1150.5, 1150.625, 1150.75, 
    1150.875, 1151, 1151.125, 1151.25, 1151.375, 1151.5, 1151.625, 1151.75, 
```

`1149.875` is missing from the band files. 

Let's look at B2 to B3 transition:
last several B2 channel  numbers
```
    10422, 10423, 10424, 10425, 10426, 10427, 10428, 10429, 10430, 10431, 
    10432, 10433, 10434, 10435, 10436, 10437, 10438, 10439 ;
```
and last several B2 wavenumbers:
```
   1947.875, 1948, 1948.125, 1948.25, 1948.375, 1948.5, 1948.625, 1948.75, 
    1948.875, 1949, 1949.125, 1949.25, 1949.375, 1949.5, 1949.625, 1949.75, _ ;

```
Interestingly, there's an "empty" value here at the end of B2, suggesting an offset by 1 issue. 

Let's look at B3:
channel numbers at the beginning
```
 Sensor_Channel = 10440, 10441, 10442, 10443, 10444, 10445, 10446, 10447, 
    10448, 10449, 10450, 10451, 10452, 10453, 10454, 10455, 10456, 10457, 
```
wavenumbers:
```
 Wavenumber = 1950, 1950.125, 1950.25, 1950.375, 1950.5, 1950.625, 1950.75, 
    1950.875, 1951, 1951.125, 1951.25, 1951.375, 1951.5, 1951.625, 1951.75, 
```

So also missing `1949.875` here too.

Let's look at the end of B3 for completeness:
Last several channel numbers
```
   13228, 13229, 13230, 13231, 13232, 13233, 13234, 13235, 13236, 13237, 
    13238, 13239 ;
```
Last wavenumbers:
```
   2297.875, 2298, 2298.125, 2298.25, 2298.375, 2298.5, 2298.625, 2298.75, 
    2298.875, 2299, 2299.125, 2299.25, 2299.375, 2299.5, 2299.625, 2299.75, _ ;
```
Same issue with an empty value. 

Let's just skip to the end of B4:
```
   16908, 16909, 16910, 16911, 16912, 16913, 16914, 16915, 16916, 16917, 
    16918, 16919, 16920 ;
```
wavenumbers:
```
   2758.875, 2759, 2759.125, 2759.25, 2759.375, 2759.5, 2759.625, 2759.75, 
    _, _ ;
```
Two empty values.      So this is a starting point.  Next I'll look at the code that was used to generate / concatenate the bands,

**Comment by BenjaminTJohnson** [comment]
binary files contain the same issue, so it's not a netcdf vs. binary issue.

**Comment by BenjaminTJohnson** [comment]
Update: I'm working on fixing the band files so I can re-concatenate them into a corrected file.   The TauCoeff files seem unaffected.   The basic strategy is to shift B2, B3, and B4 variables (that depend on n_channels) by 1, and insert the correct value into the beginning slot (this avoids having to completely recompute everything, but should be quite close numerically).

**Comment by BenjaminTJohnson** [comment]
@wx20jjung Jim, please have a look at the updated iasi-ng coefficients.  BE = big endian, LE = little endian format, rename as needed. 

https://bin.ssec.wisc.edu/pub/s4/CRTM/file/updated_iasi-ng_11152024.tgz

Let me know if you see any unexpected behavior, particularly in the boundaries between bands.

**Comment by wx20jjung** [comment]
@BenjaminTJohnson  Ben,  NCEP plans to use a 500 channel subset for IASI-NG that is similar to the current IASI 500 channel subset.  I printed out the wavenumbers for this subset from IASI and IASI-NG.  They are now identical, as expected.
